#
# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/klteduos/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/klteduos
    
PRODUCT_COPY_FILES += \
    vendor/samsung/klteduos/proprietary/vendor/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril-dsds.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libsec-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsec-ril.so \
    vendor/samsung/klteduos/proprietary/vendor/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    vendor/samsung/klteduos/proprietary/vendor/bin/hci_qcomm_init:$(TARGET_COPY_OUT_VENDOR)/bin/hci_qcomm_init \
    vendor/samsung/klteduos/proprietary/vendor/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/bin/efsks \
    vendor/samsung/klteduos/proprietary/vendor/bin/ks:$(TARGET_COPY_OUT_VENDOR)/bin/ks \
    vendor/samsung/klteduos/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/samsung/klteduos/proprietary/vendor/bin/mpdecision:$(TARGET_COPY_OUT_VENDOR)/bin/mpdecision \
    vendor/samsung/klteduos/proprietary/vendor/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/bin/qcks \
    vendor/samsung/klteduos/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/samsung/klteduos/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    vendor/samsung/klteduos/proprietary/vendor/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    vendor/samsung/klteduos/proprietary/vendor/bin/rfs_access:$(TARGET_COPY_OUT_VENDOR)/bin/rfs_access \
    vendor/samsung/klteduos/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    vendor/samsung/klteduos/proprietary/vendor/bin/time_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/time_daemon \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/C16QL_Isp0_s5k2p2xx.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/C16QL_Isp0_s5k2p2xx.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/C16QL_Isp1_s5k2p2xx.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/C16QL_Isp1_s5k2p2xx.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/F16QL_Isp0_s5k2p2xx.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/F16QL_Isp0_s5k2p2xx.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/F16QL_Isp1_s5k2p2xx.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/F16QL_Isp1_s5k2p2xx.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/F16QS_Isp0_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/F16QS_Isp0_imx240.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/F16QS_Isp1_imx240.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/F16QS_Isp1_imx240.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/Master0.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/Master0.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/Master1.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/Master1.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/cal_data_LSCmaster.bin:$(TARGET_COPY_OUT_VENDOR)/cameradata/cal_data_LSCmaster.bin \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/datapattern_420sp.yuv:$(TARGET_COPY_OUT_VENDOR)/cameradata/datapattern_420sp.yuv \
    vendor/samsung/klteduos/proprietary/vendor/cameradata/datapattern_front_420sp.yuv:$(TARGET_COPY_OUT_VENDOR)/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/C16QL_s5k2p2xx_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/C16QL_s5k2p2xx_module_info.xml \
    vendor/samsung/klteduos/proprietary/vendor/etc/F16QL_s5k2p2xx_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/F16QL_s5k2p2xx_module_info.xml \
    vendor/samsung/klteduos/proprietary/vendor/etc/F16QS_imx240_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/F16QS_imx240_module_info.xml \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/samsung/klteduos/proprietary/vendor/firmware/audience-es705-fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/audience-es705-fw.bin \
    vendor/samsung/klteduos/proprietary/vendor/firmware/audience-es705-vs.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/audience-es705-vs.bin \
    vendor/samsung/klteduos/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/klteduos/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/klteduos/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/bcmdhd_ibss.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_mfg.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_mfg.txt_a0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_a0 \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_mfg.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_mfg.txt_semco3rd:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_mfg.txt_semco3rd \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_net.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_net.txt_a0:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_a0 \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_net.txt_murata:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/klteduos/proprietary/vendor/etc/wifi/nvram_net.txt_semco3rd:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram_net.txt_semco3rd \
    vendor/samsung/klteduos/proprietary/vendor/lib/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbtnv.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libTsAe.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libTsAe.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libTsAf.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libTsAf.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libTs_J_Accm.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libTs_J_Accm.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libTs_J_Awb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_default_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_golfshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_golfshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hdr_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hdr_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hdr_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hdr_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hdr_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hdr_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hdr_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hdr_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hdr_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hfr_1080p_b.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hfr_1080p_b.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hfr_1080p_s.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hfr_1080p_s.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_hfr_120.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_pip.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_shotmode_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_shotmode_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_shotmode_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_shotmode_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_snapshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_vt.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_vt_hd.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libTsAe.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libTsAe.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libTsAf.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libTsAf.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libTs_J_Accm.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libTs_J_Accm.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libTs_J_Awb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_default_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_golfshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_golfshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hdr_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hdr_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hdr_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hdr_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hdr_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hdr_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hdr_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hdr_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hdr_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hfr_1080p_b.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hfr_1080p_b.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hfr_1080p_s.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hfr_1080p_s.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_hfr_120.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_lowres_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_lowres_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_pip.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_shotmode_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_shotmode_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_shotmode_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_shotmode_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_snapshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_vt.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_vt_hd.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libTsAe.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libTsAe.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libTsAf.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libTsAf.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libTs_J_Accm.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libTs_J_Accm.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libTs_J_Awb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_default_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_golfshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_golfshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hdr_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hdr_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hdr_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hdr_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hdr_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hdr_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hdr_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hdr_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hdr_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hfr_1080p_b.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hfr_1080p_b.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hfr_1080p_s.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hfr_1080p_s.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_hfr_120.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_liveshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_lowres_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_lowres_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_pip.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_shotmode_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_shotmode_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_shotmode_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_shotmode_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_snapshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_uhd_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_vt.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_vt_hd.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/hw/camera.vendor.msm8974.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.msm8974.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/hw/sensors.vendor.msm8974.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.vendor.msm8974.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libTsAe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTsAe.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libTsAf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTsAf.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libTs_J_Accm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTs_J_Accm.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libTs_J_Awb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTs_J_Awb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libarcsoft_nighthawk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_nighthawk.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libhr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhr.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libliveframework.so:$(TARGET_COPY_OUT_VENDOR)/lib/libliveframework.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_cac3_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_cac3_lib.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_fidelix_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_fidelix_eeprom.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_interface.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libvdis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvdis.so \
    vendor/samsung/klteduos/proprietary/vendor/bin/thermal-engine:$(TARGET_COPY_OUT_VENDOR)/bin/thermal-engine \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0797.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0797.hcd \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0797_murata.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0797_murata.hcd \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0797_semco.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0797_semco.hcd \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0797_semco3rd.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0797_semco3rd.hcd \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0797_semcosh.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0797_semcosh.hcd \
    vendor/samsung/klteduos/proprietary/vendor/firmware/bcm4350_V0395.0798_wisol.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4350_V0395.0798_wisol.hcd \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_common.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_common_res0.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_common_res1.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_common_res2.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_common_res2.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/C16QL_libchromatix_s5k2p2xx_common_res3.so:$(TARGET_COPY_OUT_VENDOR)/lib/C16QL_libchromatix_s5k2p2xx_common_res3.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_common.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_common_res0.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_common_res1.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_common_res2.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_common_res2.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QL_libchromatix_s5k2p2xx_common_res3.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QL_libchromatix_s5k2p2xx_common_res3.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_common.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_common_res0.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_common_res1.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_common_res2.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_common_res2.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/F16QS_libchromatix_imx240_common_res3.so:$(TARGET_COPY_OUT_VENDOR)/lib/F16QS_libchromatix_imx240_common_res3.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_ak7345_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7345_camcorder.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_ak7345_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7345_camera.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_camcorder.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_dw9714_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_camera.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_dw9716_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9716_camcorder.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_dw9716_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9716_camera.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_wv560_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_wv560_camcorder.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libactuator_wv560_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_wv560_camera.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_common.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_pip.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_preview.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_smart_stay.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_smart_stay.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_snapshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_video.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_vt.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_vt_beauty.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_vt_beauty.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_vt_hd.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libchromatix_s5k8b1yx_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k8b1yx_zslshot.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdrmdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdiag.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libfastcvadsp_stub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvadsp_stub.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_companion_imx240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_companion_imx240.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_companion_s5k2p2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_companion_s5k2p2xx.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib_faceproc_adspstub.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_imx240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx240.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_s5k2p2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k2p2xx.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libmmcamera_s5k8b1yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k8b1yx.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalioctl.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/rfsa/adsp/libadsp_fd_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libadsp_fd_skel.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/soundfx/libqcbassboost.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcbassboost.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/soundfx/libqcreverb.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcreverb.so \
    vendor/samsung/klteduos/proprietary/vendor/lib/soundfx/libqcvirt.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    libtime_genoff \
    TimeService

PRODUCT_PACKAGES += \
    nfc_nci.msm8974
